"""add user_id to applications

Revision ID: 687202fbff9d
Revises: 47ff925ea6b6
Create Date: 2026-09-22 20:48:34.694803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687202fbff9d'
down_revision: Union[str, None] = '47ff925ea6b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('user_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'user_id')
    # ### end Alembic commands ###
